### ISSUE TITLE
Add PHP 8.2 images

### ISSUE THREAD

**Issue by deluxetom** [dlxmedia/docker-symfony#2]
- Create new folder for PHP `8.2` and `8.2-swoole` (not sure swoole supports 8.2 yet)
- Add new build in circleCI config
- Same PHP extensions as 8.1

**Comment by deluxetom** [comment]
it's going to be probably a lot of copy / paste from 8.1 but you can check with circle CI if they build correctly:
https://app.circleci.com/pipelines/github/dlxmedia/docker-symfony

**Comment by GjorgjiTashkovski** [comment]
@thomaspicquet
Swoole: There is `phpswoole/swoole:php8.2-alpine`
Build: I had to add `linux-headers` package for both `8.2` and `8.2-swoole`

**Comment by deluxetom** [comment]
Thanks, I'll test the images by updating apps now ;)
